### ISSUE TITLE
pip install ansible fail on CentOS6

### ISSUE THREAD

**Issue by amotoki** [josug-book1-materials/chapter11#23]
On centos6 (such as step-server), ansible --version does not work after installing ansible 1.8.1 with pip without virtualenv.

環境

```
[root@step-server ~]# which pip
/usr/bin/pip
[root@step-server ~]# pip --version
pip 1.3.1 from /usr/lib/python2.6/site-packages (python 2.6)
[root@step-server ~]# cat /etc/centos-release
CentOS release 6.6 (Final)
```

virtualenv を使わずに pip でインストールする。
途中で pycrypto が再インストールされている点に注意。

```
[root@step-server ~]# pip install ansible
Downloading/unpacking ansible
  Downloading ansible-1.8.1.tar.gz (751kB): 751kB downloaded
  Running setup.py egg_info for package ansible
    no previously-included directories found matching 'lib/ansible/modules/core/.git'
    no previously-included directories found matching 'lib/ansible/modules/extras/.git'
Requirement already satisfied (use --upgrade to upgrade): paramiko in /usr/lib/python2.6/site-packages (from ansible)
Downloading/unpacking jinja2 (from ansible)
  Downloading Jinja2-2.7.3.tar.gz (378kB): 378kB downloaded
  Running setup.py egg_info for package jinja2
    warning: no files found matching '*' under directory 'custom_fixers'
    warning: no previously-included files matching '*' found under directory 'docs/_build'
    warning: no previously-included files matching '*.pyc' found under directory 'jinja2'
    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    warning: no previously-included files matching '*.pyo' found under directory 'jinja2'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
Requirement already satisfied (use --upgrade to upgrade): PyYAML in /usr/lib64/python2.6/site-packages (from ansible)
Requirement already satisfied (use --upgrade to upgrade): distribute in /usr/lib/python2.6/site-packages (from ansible)
Downloading/unpacking pycrypto>=2.6 (from ansible)
  Downloading pycrypto-2.6.1.tar.gz (446kB): 446kB downloaded
  Running setup.py egg_info for package pycrypto
Downloading/unpacking markupsafe (from jinja2->ansible)
  Downloading MarkupSafe-0.23.tar.gz
  Running setup.py egg_info for package markupsafe
Installing collected packages: ansible, jinja2, pycrypto, markupsafe
  Running setup.py install for ansible
    changing mode of build/scripts-2.6/ansible from 644 to 755
    changing mode of build/scripts-2.6/ansible-playbook from 644 to 755
    changing mode of build/scripts-2.6/ansible-pull from 644 to 755
    changing mode of build/scripts-2.6/ansible-doc from 644 to 755
    changing mode of build/scripts-2.6/ansible-galaxy from 644 to 755
    changing mode of build/scripts-2.6/ansible-vault from 644 to 755
    no previously-included directories found matching 'lib/ansible/modules/core/.git'
    no previously-included directories found matching 'lib/ansible/modules/extras/.git'
    changing mode of /usr/bin/ansible to 755
    changing mode of /usr/bin/ansible-galaxy to 755
    changing mode of /usr/bin/ansible-pull to 755
    changing mode of /usr/bin/ansible-playbook to 755
    changing mode of /usr/bin/ansible-doc to 755
    changing mode of /usr/bin/ansible-vault to 755
  Running setup.py install for jinja2
    warning: no files found matching '*' under directory 'custom_fixers'
    warning: no previously-included files matching '*' found under directory 'docs/_build'
    warning: no previously-included files matching '*.pyc' found under directory 'jinja2'
    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    warning: no previously-included files matching '*.pyo' found under directory 'jinja2'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
  Found existing installation: pycrypto 2.0.1
    Uninstalling pycrypto:
      Successfully uninstalled pycrypto
  Running setup.py install for pycrypto
    checking for gcc... gcc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables...
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed

.....

Successfully installed ansible jinja2 pycrypto markupsafe
Cleaning up...
```

バージョンを確認しようとすると、Traceback が出る。

```
[root@step-server ~]# ansible --version
Traceback (most recent call last):
  File "/usr/bin/ansible", line 25, in <module>
    from ansible.runner import Runner
  File "/usr/lib/python2.6/site-packages/ansible/runner/__init__.py", line 62, in <module>
    from Crypto.Random import atfork
  File "/usr/lib64/python2.6/site-packages/Crypto/Random/__init__.py", line 29, in <module>
    from Crypto.Random import _UserFriendlyRNG
  File "/usr/lib64/python2.6/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 38, in <module>
    from Crypto.Random.Fortuna import FortunaAccumulator
  File "/usr/lib64/python2.6/site-packages/Crypto/Random/Fortuna/FortunaAccumulator.py", line 39, in <module>
    import FortunaGenerator
  File "/usr/lib64/python2.6/site-packages/Crypto/Random/Fortuna/FortunaGenerator.py", line 34, in <module>
    from Crypto.Util.number import ceil_shift, exact_log2, exact_div
  File "/usr/lib64/python2.6/site-packages/Crypto/Util/number.py", line 56, in <module>
    if _fastmath is not None and not _fastmath.HAVE_DECL_MPZ_POWM_SEC:
AttributeError: 'module' object has no attribute 'HAVE_DECL_MPZ_POWM_SEC'
```

インストールされているバージョンは以下。

```
[root@step-server ~]# pip freeze | grep -iE '(ansible|jinja2|pycrypto|markupsafe)'
Jinja2==2.7.3
MarkupSafe==0.23
ansible==1.8.1
pycrypto==2.6.1
```

ここでマジック。CentOS6 の RPM で python-crypto を入れなおすと、なぜかちゃんと動くようになる。
yum reinstall すると、他の依存RPMを変更せずに入れ直せる。

```

[root@step-server ~]# yum reinstall python-crypto
Loaded plugins: fastestmirror, security
Setting up Reinstall Process
Loading mirror speeds from cached hostfile
 * base: ftp.tsukuba.wide.ad.jp
 * epel: ftp.tsukuba.wide.ad.jp
 * extras: ftp.tsukuba.wide.ad.jp
 * updates: ftp.tsukuba.wide.ad.jp
Resolving Dependencies
--> Running transaction check
---> Package python-crypto.x86_64 0:2.0.1-22.el6 will be reinstalled
--> Finished Dependency Resolution

Dependencies Resolved

=============================================================================================================================================================================
 Package                                      Arch                                  Version                                        Repository                           Size
=============================================================================================================================================================================
Reinstalling:
 python-crypto                                x86_64                                2.0.1-22.el6                                   base                                159 k

Transaction Summary
=============================================================================================================================================================================
Reinstall     1 Package(s)

Total download size: 159 k
Installed size: 565 k
Is this ok [y/N]: y
Downloading Packages:
python-crypto-2.0.1-22.el6.x86_64.rpm                                                                                                                 | 159 kB     00:00
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing : python-crypto-2.0.1-22.el6.x86_64                                                                                                                         1/1
  Verifying  : python-crypto-2.0.1-22.el6.x86_64                                                                                                                         1/1

Installed:
  python-crypto.x86_64 0:2.0.1-22.el6

Complete!
[root@step-server ~]# ansible --version
ansible 1.8.1
  configured module search path = None
```

おお、ちゃんと表示できた。

pip freeze 上は、新しいバージョンが表示されている。たぶんこれは関係ない。

```
[root@step-server ~]# pip freeze | grep -iE '(ansible|jinja2|pycrypto|markupsafe)'
Jinja2==2.7.3
MarkupSafe==0.23
ansible==1.8.1
pycrypto==2.6.1
```

**Comment by amotoki** [comment]
古すぎるのでクローズする
